name: env_stockpicking_screener
channels:
  - conda-forge
  - plotly

dependencies:
  - conda-build
  - ipykernel
  - jupyterlab
  - plotly>=5.5.0
  - pandas
  - pip
  - pytask>=0.0.14
  - pytask-latex>=0.0.12

  - pytask-r>=0.0.9

  - pytest
  - pytest-cov
  - python=3.9
  - python-graphviz

  - virtualenv=20.0.33

  - pip:

    - pre-commit

    - kaleido
    - sphinx
    - sphinx-autobuild
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex

    - numpy
    - urllib3
    - yfinance
    - statsmodels
    - intrinio_sdk
    - pandas-datareader
    - dash_renderer


    - beautifulsoup4
    - selenium


    - Brotli==1.0.9
    - certifi==2021.10.8
    - charset-normalizer==2.0.12
    - click==8.0.4
    - colorama==0.4.4
    - dash==2.2.0
    - dash-bootstrap-components==1.0.3
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - Flask==2.0.3
    - Flask-Compress==1.10.1
    - gunicorn==20.1.0
    - idna==3.3
    - itsdangerous==2.1.0
    - Jinja2==3.0.3
    - lxml==4.8.0
    - MarkupSafe==2.1.0
    - multitasking==0.0.10
    - numpy==1.22.2
    - pandas==1.4.1
    - pandas-datareader==0.10.0
    - plotly==5.6.0
    - python-dateutil==2.8.2
    - pytz==2021.3
    - requests==2.27.1
    - six==1.16.0
    - tenacity==8.0.1
    - urllib3==1.26.8
    - Werkzeug==2.0.3
    - yfinance==0.1.70